#!/bin/bash
which python
python3 manage.py migrate
python3 /app/manage.py collectstatic --noinput
# /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:80 --chdir=/app

# gunicorn -b 0.0.0.0 config.asgi:application --preload -w 4 -k uvicorn.workers.UvicornWorker
python3 manage.py runserver 0:8000