version: '3'

services:
  django:
    container_name: rest_api
    build:
        context: .
        dockerfile: ./compose/local/django/Dockerfile
    image: drftest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # env_file:
    #   - ./.envs/.local
    command: sh /app/compose/local/django/start
    tty: true

  front-envoy:
    container_name: vue_front
    build:
        context: .
        dockerfile: ./compose/local/vue/Dockerfile
    image: vuetest
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    # env_file:
    #   - ./.envs/.local
    command: sh /app/compose/local/vue/start
    tty: true
#   nginx:
#     restart: always
#     images: drftest
#     build: ./nginx/
#     ports:
#       - "80:80"
#     volumes:
#       - web-static:/www/static
#     links:
#       - web:web





# volumes:
#   web-django:
#   web-static:
#   pgdata:
#   redisdata: